name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  # Comment out to enable these permissions if needed.
  # packages: write
  # deployments: write
  # id-token: write

jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      # Get next version
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: draft_release
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-deno-with-cache
      - name: Compile assets
        run: |
          deno task compile:linux-amd64
          deno task compile:darwin-amd64
          deno task compile:darwin-arm64
      - name: Upload assets
        run: |
          gh release upload ${{ needs.draft_release.outputs.tag_name }} ./dist/gh-workflow-ls-* --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

